services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-manager
    restart: unless-stopped
    ports:
      - "8002:8002"
    volumes:
      - /var/lib/project-manager/data:/var/lib/project-manager/data
    environment:
      - NODE_ENV=production
      - PORT=8002
